import { Product } from "../types/Product";

export const fakeData: Product[] = [
  {
    id: 3,
    description: "Mangá One Piece cheio de aventuras",
    name: "Mangá One Piece vol.1",
    price: 19.99,
    categoria: "Aventura",
  },
  {
    id: 4,
    description: "Mangá Attack on Titan cheio de suspense",
    name: "Mangá Attack on Titan vol.1",
    price: 18.99,
    categoria: "Suspense",
  },
  {
    id: 5,
    description: "Mangá Dragon Ball Z com muita ação",
    name: "Mangá Dragon Ball Z vol.1",
    price: 22.99,
    categoria: "Ação",
  },
  {
    id: 6,
    description: "Mangá My Hero Academia cheio de heroísmo",
    name: "Mangá My Hero Academia vol.1",
    price: 17.99,
    categoria: "Ação",
  },
  {
    id: 7,
    description: "Mangá Death Note repleto de mistério",
    name: "Mangá Death Note vol.1",
    price: 16.99,
    categoria: "Mistério",
  },
  {
    id: 8,
    description: "Mangá Fullmetal Alchemist com uma história cativante",
    name: "Mangá Fullmetal Alchemist vol.1",
    price: 21.99,
    categoria: "Aventura",
  },
  {
    id: 9,
    description: "Mangá Tokyo Ghoul com muita ação e horror",
    name: "Mangá Tokyo Ghoul vol.1",
    price: 18.49,
    categoria: "Ação",
  },
  {
    id: 10,
    description: "Mangá One Punch Man cheio de comédia e ação",
    name: "Mangá One Punch Man vol.1",
    price: 20.49,
    categoria: "Ação",
  },
  {
    id: 11,
    description: "Mangá Hunter x Hunter repleto de aventuras",
    name: "Mangá Hunter x Hunter vol.1",
    price: 19.99,
    categoria: "Aventura",
  },
  {
    id: 12,
    description: "Mangá Fairy Tail com muita magia e amizade",
    name: "Mangá Fairy Tail vol.1",
    price: 18.99,
    categoria: "Fantasia",
  },
  {
    id: 13,
    description: "Mangá Bleach cheio de batalhas épicas",
    name: "Mangá Bleach vol.1",
    price: 17.99,
    categoria: "Ação",
  },
  {
    id: 14,
    description: "Mangá Demon Slayer com uma arte incrível",
    name: "Mangá Demon Slayer vol.1",
    price: 21.99,
    categoria: "Ação",
  },
  {
    id: 15,
    description: "Mangá Black Clover cheio de magia e aventura",
    name: "Mangá Black Clover vol.1",
    price: 19.99,
    categoria: "Fantasia",
  },
  {
    id: 16,
    description: "Mangá Haikyuu!! com muita energia e esporte",
    name: "Mangá Haikyuu!! vol.1",
    price: 18.49,
    categoria: "Esporte",
  },
  {
    id: 17,
    description: "Mangá Promised Neverland cheio de suspense",
    name: "Mangá Promised Neverland vol.1",
    price: 20.49,
    categoria: "Suspense",
  },
];

export const categories = [
  "Aventura",
  "Suspense",
  "Ação",
  "Mistério",
  "Fantasia",
  "Esporte",
];
